--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Clothes_Male.xls

local Clothes_MaleXls = {
    Clothes = {
        [1] = {
            Male_Cloth_Part = 'Clothes',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Clothes',
            Value = 2,
            Des = 'Male_Chest_TshirtShort_A001'
        },
        [3] = {
            Male_Cloth_Part = 'Clothes',
            Value = 3,
            Des = 'Male_Chest_TshirtShort_A002'
        },
        [4] = {
            Male_Cloth_Part = 'Clothes',
            Value = 4,
            Des = 'Male_Chest_TshirtShort_A003'
        },
        [5] = {
            Male_Cloth_Part = 'Clothes',
            Value = 5,
            Des = 'Male_Chest_TshirtShort_A004'
        },
        [6] = {
            Male_Cloth_Part = 'Clothes',
            Value = 6,
            Des = 'Male_Chest_TshirtShort_A005'
        },
        [7] = {
            Male_Cloth_Part = 'Clothes',
            Value = 7,
            Des = 'Male_Chest_TshirtShort_A006'
        },
        [8] = {
            Male_Cloth_Part = 'Clothes',
            Value = 8,
            Des = 'Male_Chest_TshirtShort_A007'
        },
        [9] = {
            Male_Cloth_Part = 'Clothes',
            Value = 9,
            Des = 'Male_Chest_TshirtShort_A008'
        },
        [10] = {
            Male_Cloth_Part = 'Clothes',
            Value = 10,
            Des = 'Male_Chest_TshirtShort_A009'
        },
        [11] = {
            Male_Cloth_Part = 'Clothes',
            Value = 11,
            Des = 'Male_Chest_TshirtShort_A010'
        },
        [12] = {
            Male_Cloth_Part = 'Clothes',
            Value = 12,
            Des = 'Male_001Jacket'
        },
        [13] = {
            Male_Cloth_Part = 'Clothes',
            Value = 13,
            Des = 'Male_Jacket_Leis01'
        },
        [14] = {
            Male_Cloth_Part = 'Clothes',
            Value = 14,
            Des = 'RedJacket'
        },
        [15] = {
            Male_Cloth_Part = 'Clothes',
            Value = 15,
            Des = 'Male_Jacket_Leis02'
        },
        [16] = {
            Male_Cloth_Part = 'Clothes',
            Value = 16,
            Des = 'Male_Jacket_Leis03'
        },
        [17] = {
            Male_Cloth_Part = 'Clothes',
            Value = 17,
            Des = 'Male_006Jacket'
        },
        [18] = {
            Male_Cloth_Part = 'Clothes',
            Value = 18,
            Des = 'Male_007Jacket'
        },
        [19] = {
            Male_Cloth_Part = 'Clothes',
            Value = 19,
            Des = 'Male_008Tshirt'
        },
        [20] = {
            Male_Cloth_Part = 'Clothes',
            Value = 20,
            Des = 'Male_009Jacket'
        },
        [21] = {
            Male_Cloth_Part = 'Clothes',
            Value = 21,
            Des = 'Male_010Tshirt'
        },
        [22] = {
            Male_Cloth_Part = 'Clothes',
            Value = 22,
            Des = 'Male_011Tshirt'
        },
        [23] = {
            Male_Cloth_Part = 'Clothes',
            Value = 23,
            Des = 'Male_012Jacket'
        },
        [24] = {
            Male_Cloth_Part = 'Clothes',
            Value = 24,
            Des = 'Male_AviatorJacket'
        },
        [25] = {
            Male_Cloth_Part = 'Clothes',
            Value = 25,
            Des = 'Male_MexicJacket'
        },
        [26] = {
            Male_Cloth_Part = 'Clothes',
            Value = 26,
            Des = 'Male_SpaceJacket'
        },
        [27] = {
            Male_Cloth_Part = 'Clothes',
            Value = 27,
            Des = 'Male_BaseballJacket'
        },
        [28] = {
            Male_Cloth_Part = 'Clothes',
            Value = 28,
            Des = 'Male_UniverJacket'
        },
        [29] = {
            Male_Cloth_Part = 'Clothes',
            Value = 29,
            Des = 'Male_UniverJacket_01'
        },
        [30] = {
            Male_Cloth_Part = 'Clothes',
            Value = 30,
            Des = 'Male_OwlJacket'
        },
        [31] = {
            Male_Cloth_Part = 'Clothes',
            Value = 31,
            Des = 'Male_Chest_ArmorGriffin_001'
        },
        [32] = {
            Male_Cloth_Part = 'Clothes',
            Value = 32,
            Des = 'Unisex_Chest_ArmorIron_001'
        },
        [33] = {
            Male_Cloth_Part = 'Clothes',
            Value = 33,
            Des = 'Male_WendigoJacket'
        },
        [34] = {
            Male_Cloth_Part = 'Clothes',
            Value = 34,
            Des = 'Male_NutJacket'
        },
        [35] = {
            Male_Cloth_Part = 'Clothes',
            Value = 35,
            Des = 'Male_Chest_UniformPolice_001'
        },
        [36] = {
            Male_Cloth_Part = 'Clothes',
            Value = 36,
            Des = 'Male_Chest_TshitSki_001'
        },
        [37] = {
            Male_Cloth_Part = 'Clothes',
            Value = 37,
            Des = 'Male_Chest_JacketRobtDog_001'
        },
        [38] = {
            Male_Cloth_Part = 'Clothes',
            Value = 38,
            Des = 'Male_Chest_MuscleSuitShark_001'
        },
        [39] = {
            Male_Cloth_Part = 'Clothes',
            Value = 39,
            Des = 'Male_Chest_MuscleSuitShark_002'
        },
        [40] = {
            Male_Cloth_Part = 'Clothes',
            Value = 40,
            Des = 'Male_Chest_TshirtWaste_001'
        },
        [41] = {
            Male_Cloth_Part = 'Clothes',
            Value = 41,
            Des = 'Male_Chest_JacketBiker_001'
        },
        [42] = {
            Male_Cloth_Part = 'Clothes',
            Value = 42,
            Des = 'Male_Chest_TshirtSteam_001'
        },
        [43] = {
            Male_Cloth_Part = 'Clothes',
            Value = 43,
            Des = 'Male_Chest_JacketRobtEva_001'
        },
        [44] = {
            Male_Cloth_Part = 'Clothes',
            Value = 44,
            Des = 'Male_Zombies01Tshirt'
        },
        [45] = {
            Male_Cloth_Part = 'Clothes',
            Value = 45,
            Des = 'Male_Zombies03Jacket'
        },
        [46] = {
            Male_Cloth_Part = 'Clothes',
            Value = 46,
            Des = 'Male_Zombies04Tshirt'
        },
        [47] = {
            Male_Cloth_Part = 'Clothes',
            Value = 47,
            Des = 'Male_Zombies06Jacket'
        }
    },
    Trousers = {
        [1] = {
            Male_Cloth_Part = 'Trousers',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Trousers',
            Value = 2,
            Des = 'Male_Jeans01Trousers'
        },
        [3] = {
            Male_Cloth_Part = 'Trousers',
            Value = 3,
            Des = 'Male_Leis01Trousers'
        },
        [4] = {
            Male_Cloth_Part = 'Trousers',
            Value = 4,
            Des = 'Male_003Trousers'
        },
        [5] = {
            Male_Cloth_Part = 'Trousers',
            Value = 5,
            Des = 'Male_Leis01Pants'
        },
        [6] = {
            Male_Cloth_Part = 'Trousers',
            Value = 6,
            Des = 'Male_Leis03Trousers'
        },
        [7] = {
            Male_Cloth_Part = 'Trousers',
            Value = 7,
            Des = 'Male_006Trousers'
        },
        [8] = {
            Male_Cloth_Part = 'Trousers',
            Value = 8,
            Des = 'Male_007Trousers'
        },
        [9] = {
            Male_Cloth_Part = 'Trousers',
            Value = 9,
            Des = 'Male_008Trousers'
        },
        [10] = {
            Male_Cloth_Part = 'Trousers',
            Value = 10,
            Des = 'Male_009Trousers'
        },
        [11] = {
            Male_Cloth_Part = 'Trousers',
            Value = 11,
            Des = 'Male_010Trousers'
        },
        [12] = {
            Male_Cloth_Part = 'Trousers',
            Value = 12,
            Des = 'Male_011Trousers'
        },
        [13] = {
            Male_Cloth_Part = 'Trousers',
            Value = 13,
            Des = 'Male_012Pants'
        },
        [14] = {
            Male_Cloth_Part = 'Trousers',
            Value = 14,
            Des = 'Male_AviatorTrousers'
        },
        [15] = {
            Male_Cloth_Part = 'Trousers',
            Value = 15,
            Des = 'Male_MexicTrousers'
        },
        [16] = {
            Male_Cloth_Part = 'Trousers',
            Value = 16,
            Des = 'Male_SpaceTrousers'
        },
        [17] = {
            Male_Cloth_Part = 'Trousers',
            Value = 17,
            Des = 'Male_BaseballTrousers'
        },
        [18] = {
            Male_Cloth_Part = 'Trousers',
            Value = 18,
            Des = 'Male_UniverTrousers'
        },
        [19] = {
            Male_Cloth_Part = 'Trousers',
            Value = 19,
            Des = 'Male_UniverTrousers_01'
        },
        [20] = {
            Male_Cloth_Part = 'Trousers',
            Value = 20,
            Des = 'Male_OwlTrousers'
        },
        [21] = {
            Male_Cloth_Part = 'Trousers',
            Value = 21,
            Des = 'Male_Leg_ArmorGriffin_001'
        },
        [22] = {
            Male_Cloth_Part = 'Trousers',
            Value = 22,
            Des = 'Male_Leg_ArmorIron_001'
        },
        [23] = {
            Male_Cloth_Part = 'Trousers',
            Value = 23,
            Des = 'Male_WendigoTrousers'
        },
        [24] = {
            Male_Cloth_Part = 'Trousers',
            Value = 24,
            Des = 'Male_NutTrousers'
        },
        [25] = {
            Male_Cloth_Part = 'Trousers',
            Value = 25,
            Des = 'Male_Leg_PantsLPolice_001'
        },
        [26] = {
            Male_Cloth_Part = 'Trousers',
            Value = 26,
            Des = 'Male_Leg_PantsLSki_001'
        },
        [27] = {
            Male_Cloth_Part = 'Trousers',
            Value = 27,
            Des = 'Male_Leg_PantsLRobtDog_001'
        },
        [28] = {
            Male_Cloth_Part = 'Trousers',
            Value = 28,
            Des = 'Male_Leg_PantsShark_001'
        },
        [29] = {
            Male_Cloth_Part = 'Trousers',
            Value = 29,
            Des = 'Male_Leg_PantsShark_002'
        },
        [30] = {
            Male_Cloth_Part = 'Trousers',
            Value = 30,
            Des = 'Male_Leg_TrousersWaste_001'
        },
        [31] = {
            Male_Cloth_Part = 'Trousers',
            Value = 31,
            Des = 'Male_Leg_TrousersBiker_001'
        },
        [32] = {
            Male_Cloth_Part = 'Trousers',
            Value = 32,
            Des = 'Male_Leg_TrousersSteam_001'
        },
        [33] = {
            Male_Cloth_Part = 'Trousers',
            Value = 33,
            Des = 'Male_Leg_PantsLRobtEva_001'
        },
        [34] = {
            Male_Cloth_Part = 'Trousers',
            Value = 34,
            Des = 'Male_Zombies01Pants'
        },
        [35] = {
            Male_Cloth_Part = 'Trousers',
            Value = 35,
            Des = 'Male_Zombies03Trousers'
        },
        [36] = {
            Male_Cloth_Part = 'Trousers',
            Value = 36,
            Des = 'Male_Zombies04Trousers'
        },
        [37] = {
            Male_Cloth_Part = 'Trousers',
            Value = 37,
            Des = 'Male_Zombies06Trousers'
        }
    },
    Hair = {
        [1] = {
            Male_Cloth_Part = 'Hair',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Hair',
            Value = 2,
            Des = 'Hair_Brown01M'
        },
        [3] = {
            Male_Cloth_Part = 'Hair',
            Value = 3,
            Des = 'Hair_Blonde01M'
        },
        [4] = {
            Male_Cloth_Part = 'Hair',
            Value = 4,
            Des = 'Hair_Orange01M'
        },
        [5] = {
            Male_Cloth_Part = 'Hair',
            Value = 5,
            Des = 'Hair_White01M'
        },
        [6] = {
            Male_Cloth_Part = 'Hair',
            Value = 6,
            Des = 'Hair_Green01M'
        },
        [7] = {
            Male_Cloth_Part = 'Hair',
            Value = 7,
            Des = 'Hair_Zombies06_M'
        }
    },
    Hands = {
        [1] = {
            Male_Cloth_Part = 'Hands',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Hands',
            Value = 2,
            Des = 'Male_GLeather01'
        },
        [3] = {
            Male_Cloth_Part = 'Hands',
            Value = 3,
            Des = 'Male_AviatorGloves'
        },
        [4] = {
            Male_Cloth_Part = 'Hands',
            Value = 4,
            Des = 'Male_SpaceGloves'
        },
        [5] = {
            Male_Cloth_Part = 'Hands',
            Value = 5,
            Des = 'Male_BaseballGloves'
        },
        [6] = {
            Male_Cloth_Part = 'Hands',
            Value = 6,
            Des = 'Male_UniverGloves'
        },
        [7] = {
            Male_Cloth_Part = 'Hands',
            Value = 7,
            Des = 'Male_UniverGloves_01'
        },
        [8] = {
            Male_Cloth_Part = 'Hands',
            Value = 8,
            Des = 'Male_OwlGloves'
        },
        [9] = {
            Male_Cloth_Part = 'Hands',
            Value = 9,
            Des = 'Unisex_Hand_GlovesGriffin_001'
        },
        [10] = {
            Male_Cloth_Part = 'Hands',
            Value = 10,
            Des = 'Unisex_Hand_GlovesIron_001'
        },
        [11] = {
            Male_Cloth_Part = 'Hands',
            Value = 11,
            Des = 'Male_WendigoGloves'
        },
        [12] = {
            Male_Cloth_Part = 'Hands',
            Value = 12,
            Des = 'Unisex_Hand_GlovesSki_001'
        },
        [13] = {
            Male_Cloth_Part = 'Hands',
            Value = 13,
            Des = 'Unisex_Hand_GlovesRobtDog_001'
        },
        [14] = {
            Male_Cloth_Part = 'Hands',
            Value = 14,
            Des = 'Male_Hand_GlovesBiker_001'
        },
        [15] = {
            Male_Cloth_Part = 'Hands',
            Value = 15,
            Des = 'Unisex_Hand_GlovesRobtEva_001'
        },
        [16] = {
            Male_Cloth_Part = 'Hands',
            Value = 16,
            Des = 'Male_Hand_GlovesSteam_001'
        }
    },
    Shoes = {
        [1] = {
            Male_Cloth_Part = 'Shoes',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Shoes',
            Value = 2,
            Des = 'LeatherShoe'
        },
        [3] = {
            Male_Cloth_Part = 'Shoes',
            Value = 3,
            Des = 'Male_Leis01Shoes'
        },
        [4] = {
            Male_Cloth_Part = 'Shoes',
            Value = 4,
            Des = 'Male_003Shoes'
        },
        [5] = {
            Male_Cloth_Part = 'Shoes',
            Value = 5,
            Des = 'Male_BLeather01'
        },
        [6] = {
            Male_Cloth_Part = 'Shoes',
            Value = 6,
            Des = 'Male_Leis03Shoes'
        },
        [7] = {
            Male_Cloth_Part = 'Shoes',
            Value = 7,
            Des = 'Male_006Shoes'
        },
        [8] = {
            Male_Cloth_Part = 'Shoes',
            Value = 8,
            Des = 'Male_007Shoes'
        },
        [9] = {
            Male_Cloth_Part = 'Shoes',
            Value = 9,
            Des = 'Male_008Shoes'
        },
        [10] = {
            Male_Cloth_Part = 'Shoes',
            Value = 10,
            Des = 'Male_009Shoes'
        },
        [11] = {
            Male_Cloth_Part = 'Shoes',
            Value = 11,
            Des = 'Unisex_Feet_BasketballShoes_003'
        },
        [12] = {
            Male_Cloth_Part = 'Shoes',
            Value = 12,
            Des = 'Male_010Shoes'
        },
        [13] = {
            Male_Cloth_Part = 'Shoes',
            Value = 13,
            Des = 'Male_011Boots'
        },
        [14] = {
            Male_Cloth_Part = 'Shoes',
            Value = 14,
            Des = 'Male_012Boots'
        },
        [15] = {
            Male_Cloth_Part = 'Shoes',
            Value = 15,
            Des = 'Male_AviatorShoes'
        },
        [16] = {
            Male_Cloth_Part = 'Shoes',
            Value = 16,
            Des = 'Male_MexicBoots'
        },
        [17] = {
            Male_Cloth_Part = 'Shoes',
            Value = 17,
            Des = 'Male_SpaceBoots'
        },
        [18] = {
            Male_Cloth_Part = 'Shoes',
            Value = 18,
            Des = 'Male_BaseballShoes'
        },
        [19] = {
            Male_Cloth_Part = 'Shoes',
            Value = 19,
            Des = 'Male_UniverShoes'
        },
        [20] = {
            Male_Cloth_Part = 'Shoes',
            Value = 20,
            Des = 'Male_UniverShoes_01'
        },
        [21] = {
            Male_Cloth_Part = 'Shoes',
            Value = 21,
            Des = 'Male_OwlBoots'
        },
        [22] = {
            Male_Cloth_Part = 'Shoes',
            Value = 22,
            Des = 'Unisex_Feet_ShoesGriffin_001'
        },
        [23] = {
            Male_Cloth_Part = 'Shoes',
            Value = 23,
            Des = 'Unisex_Feet_ShoesIron_001'
        },
        [24] = {
            Male_Cloth_Part = 'Shoes',
            Value = 24,
            Des = 'Male_WendigoShoes'
        },
        [25] = {
            Male_Cloth_Part = 'Shoes',
            Value = 25,
            Des = 'Male_NutBoots'
        },
        [26] = {
            Male_Cloth_Part = 'Shoes',
            Value = 26,
            Des = 'Unisex_Feet_ShoesPolice_001'
        },
        [27] = {
            Male_Cloth_Part = 'Shoes',
            Value = 27,
            Des = 'Unisex_Feet_BootsSki_001'
        },
        [28] = {
            Male_Cloth_Part = 'Shoes',
            Value = 28,
            Des = 'Unisex_Feet_ShoesSki_001'
        },
        [29] = {
            Male_Cloth_Part = 'Shoes',
            Value = 29,
            Des = 'Male_Feet_ShoesRobtDog_001'
        },
        [30] = {
            Male_Cloth_Part = 'Shoes',
            Value = 30,
            Des = 'Unisex_Feet_SlippersShark_001'
        },
        [31] = {
            Male_Cloth_Part = 'Shoes',
            Value = 31,
            Des = 'Male_Feet_BootsWaste_001'
        },
        [32] = {
            Male_Cloth_Part = 'Shoes',
            Value = 32,
            Des = 'Male_Feet_BootsBiker_001'
        },
        [33] = {
            Male_Cloth_Part = 'Shoes',
            Value = 33,
            Des = 'Male_Feet_BootsSteam_001'
        },
        [34] = {
            Male_Cloth_Part = 'Shoes',
            Value = 34,
            Des = 'Unisex_Feet_ShoesRobtEva_001'
        },
        [35] = {
            Male_Cloth_Part = 'Shoes',
            Value = 35,
            Des = 'Male_Zombies01Shoes'
        },
        [36] = {
            Male_Cloth_Part = 'Shoes',
            Value = 36,
            Des = 'Male_Zombies03Boots'
        },
        [37] = {
            Male_Cloth_Part = 'Shoes',
            Value = 37,
            Des = 'Male_Zombies04Boots'
        },
        [38] = {
            Male_Cloth_Part = 'Shoes',
            Value = 38,
            Des = 'Male_Zombies06Shoes'
        }
    },
    Face = {
        [1] = {
            Male_Cloth_Part = 'Face',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'Face',
            Value = 2,
            Des = 'Male_test1'
        },
        [3] = {
            Male_Cloth_Part = 'Face',
            Value = 3,
            Des = 'Male_test2'
        },
        [4] = {
            Male_Cloth_Part = 'Face',
            Value = 4,
            Des = 'Male_test3'
        },
        [5] = {
            Male_Cloth_Part = 'Face',
            Value = 5,
            Des = 'Zombies_test1Zombies01'
        },
        [6] = {
            Male_Cloth_Part = 'Face',
            Value = 6,
            Des = 'Zombies_test2'
        },
        [7] = {
            Male_Cloth_Part = 'Face',
            Value = 7,
            Des = 'Zombies_test3'
        },
        [8] = {
            Male_Cloth_Part = 'Face',
            Value = 8,
            Des = 'Zombies_test4'
        },
        [9] = {
            Male_Cloth_Part = 'Face',
            Value = 9,
            Des = 'Zombies_test5'
        },
        [10] = {
            Male_Cloth_Part = 'Face',
            Value = 10,
            Des = 'Zombies_test6'
        }
    },
    SkinColor = {
        [1] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 1,
            Des = 'DefaultMale'
        },
        [2] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 2,
            Des = 'Color2'
        },
        [3] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 3,
            Des = 'Color3'
        },
        [4] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 4,
            Des = 'Color4'
        },
        [5] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 5,
            Des = 'Color5'
        },
        [6] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 6,
            Des = 'Color6'
        },
        [7] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 7,
            Des = 'Color7'
        },
        [8] = {
            Male_Cloth_Part = 'SkinColor',
            Value = 8,
            Des = 'Color8'
        }
    },
    HeadAccessory = {
        [1] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 1,
            Des = 'Empty_Head'
        },
        [2] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 2,
            Des = 'Male_ComHat_001'
        },
        [3] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 3,
            Des = 'Male_ComHat003'
        },
        [4] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 4,
            Des = 'Male_ComHat004'
        },
        [5] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 5,
            Des = 'Male_ComHat005'
        },
        [6] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 6,
            Des = 'Male_ComHat006'
        },
        [7] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 7,
            Des = 'Male_ComHat007'
        },
        [8] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 8,
            Des = 'Male_008Hat'
        },
        [9] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 9,
            Des = 'Male_010Hat'
        },
        [10] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 10,
            Des = 'Male_011Hat'
        },
        [11] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 11,
            Des = 'Male_012Hat'
        },
        [12] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 12,
            Des = 'Male_ComHelmet003'
        },
        [13] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 13,
            Des = 'Male_ComHelmet004'
        },
        [14] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 14,
            Des = 'Male_ComHelmet005'
        },
        [15] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 15,
            Des = 'Male_013Hat'
        },
        [16] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 16,
            Des = 'Male_AviatorHat'
        },
        [17] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 17,
            Des = 'Male_MexicHat'
        },
        [18] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 18,
            Des = 'Male_SpaceHelmet'
        },
        [19] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 19,
            Des = 'Male_Baseball01Hat'
        },
        [20] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 20,
            Des = 'Male_Baseball02Hat'
        },
        [21] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 21,
            Des = 'Male_UniverHelmet'
        },
        [22] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 22,
            Des = 'Male_UniverHelmet_01'
        },
        [23] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 23,
            Des = 'Male_Owl_Helmet'
        },
        [24] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 24,
            Des = 'Male_Head_HelmetGriffin_001'
        },
        [25] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 25,
            Des = 'Unisex_Head_HelmetIron_001'
        },
        [26] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 26,
            Des = 'Male_Wendigo_Helmet'
        },
        [27] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 27,
            Des = 'Male_Nut_Helmet'
        },
        [28] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 28,
            Des = 'Unisex_Head_MaskPolice_001'
        },
        [29] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 29,
            Des = 'Unisex_Head_CapPolice_001'
        },
        [30] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 30,
            Des = 'Unisex_Head_CapSki_001'
        },
        [31] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 31,
            Des = 'Male_Head_HelmetRobtDog_001'
        },
        [32] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 32,
            Des = 'Male_Head_HelmetShark_001'
        },
        [33] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 33,
            Des = 'Male_Head_HelmetBiker_001'
        },
        [34] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 34,
            Des = 'Male_Head_HatSteam_001'
        },
        [35] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 35,
            Des = 'Unisex_Head_HelmetRobtEva_001'
        },
        [36] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 36,
            Des = 'Male_Zombies01Hat'
        },
        [37] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 37,
            Des = 'Male_Zombies03_Helmet'
        },
        [38] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 38,
            Des = 'Male_Zombies04_Helmet'
        },
        [39] = {
            Male_Cloth_Part = 'HeadAccessory',
            Value = 39,
            Des = 'Male_Zombies06_Hat'
        }
    },
    NeckAccessory = {
        [1] = {
            Male_Cloth_Part = 'NeckAccessory',
            Value = 1,
            Des = 'Empty_Neck'
        },
        [2] = {
            Male_Cloth_Part = 'NeckAccessory',
            Value = 2,
            Des = 'Male_AviatorScarf'
        },
        [3] = {
            Male_Cloth_Part = 'NeckAccessory',
            Value = 3,
            Des = 'Male_AviatorScarf_02'
        },
        [4] = {
            Male_Cloth_Part = 'NeckAccessory',
            Value = 4,
            Des = 'Male_AviatorScarf_03'
        },
        [5] = {
            Male_Cloth_Part = 'NeckAccessory',
            Value = 5,
            Des = 'Male_Zombies06_ChestSup'
        }
    },
    LegAccessory = {
        [1] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 1,
            Des = 'Empty_Legs'
        },
        [2] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 2,
            Des = 'Male_AviatorKneepad'
        },
        [3] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 3,
            Des = 'Male_OwlKneepad'
        },
        [4] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 4,
            Des = 'Unisex_Knee_PadGriffin_001'
        },
        [5] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 5,
            Des = 'Unisex_Knee_PadIron_001'
        },
        [6] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 6,
            Des = 'Unisex_Knee_PadPolice_001'
        },
        [7] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 7,
            Des = 'Unisex_Knee_PadWaste_001'
        },
        [8] = {
            Male_Cloth_Part = 'LegAccessory',
            Value = 8,
            Des = 'Unisex_Knee_PadBiker_001'
        }
    },
    HandsAccessory = {
        [1] = {
            Male_Cloth_Part = 'HandsAccessory',
            Value = 1,
            Des = 'Empty_Hands'
        },
        [2] = {
            Male_Cloth_Part = 'HandsAccessory',
            Value = 2,
            Des = 'Watch'
        },
        [3] = {
            Male_Cloth_Part = 'HandsAccessory',
            Value = 3,
            Des = 'Male_010Wrist'
        },
        [4] = {
            Male_Cloth_Part = 'HandsAccessory',
            Value = 4,
            Des = 'Male_011Wrist'
        },
        [5] = {
            Male_Cloth_Part = 'HandsAccessory',
            Value = 5,
            Des = 'Male_SteamWrist'
        }
    },
    BodyAccessory = {
        [1] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 1,
            Des = 'Empty_Body'
        },
        [2] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 2,
            Des = 'Male_009Bag'
        },
        [3] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 3,
            Des = 'Male_012Bag'
        },
        [4] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 4,
            Des = 'Female_Chest_Hobo_002'
        },
        [5] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 5,
            Des = 'Male_AviatorBag'
        },
        [6] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 6,
            Des = 'Male_MexicUkulele'
        },
        [7] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 7,
            Des = 'Male_SpaceBag'
        },
        [8] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 8,
            Des = 'Male_BaseballBag'
        },
        [9] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 9,
            Des = 'Male_UniverBag'
        },
        [10] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 10,
            Des = 'Male_WendigoBag'
        },
        [11] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 11,
            Des = 'Unisex_Back_BackpackPolice_001'
        },
        [12] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 12,
            Des = 'Unisex_Back_BackpackSki_001'
        },
        [13] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 13,
            Des = 'Female_Back_BackpackSteam_001'
        },
        [14] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 14,
            Des = 'Male_Zombies04Bag'
        },
        [15] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 15,
            Des = 'Female_Zombies05Bag'
        },
        [16] = {
            Male_Cloth_Part = 'BodyAccessory',
            Value = 16,
            Des = 'Male_Zombies06Bag'
        }
    },
    WaistAccessory = {
        [1] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 1,
            Des = 'Empty_Waist'
        },
        [2] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 2,
            Des = 'LifeBuoy'
        },
        [3] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 3,
            Des = 'Unisex_Pelvis_Lifebuoy_Duck_01'
        },
        [4] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 4,
            Des = 'Unisex_Pelvis_Lifebuoy_Donut_01'
        },
        [5] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 5,
            Des = 'Unisex_Pelvis_Lifebuoy_Donut_02'
        },
        [6] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 6,
            Des = 'Unisex_Pelvis_Lifebuoy_Watermelon'
        },
        [7] = {
            Male_Cloth_Part = 'WaistAccessory',
            Value = 7,
            Des = 'Unisex_Pelvis_Lifebuoy_Tire'
        }
    },
    FaceAccessory = {
        [1] = {
            Male_Cloth_Part = 'FaceAccessory',
            Value = 1,
            Des = 'Empty_Face'
        },
        [2] = {
            Male_Cloth_Part = 'FaceAccessory',
            Value = 2,
            Des = 'Glasses'
        },
        [3] = {
            Male_Cloth_Part = 'FaceAccessory',
            Value = 3,
            Des = 'Female_MadMax_Glasses'
        },
        [4] = {
            Male_Cloth_Part = 'FaceAccessory',
            Value = 4,
            Des = 'HeadSet'
        }
    }
}

return Clothes_MaleXls
