--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Items.xls

local ItemXls = {
    [1000] = {
        ItemID = 1000,
        Name = '皮肤1',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 1,
        Order = 1,
        CompositeTarget = nil,
        StackNum = 1,
        CompositeNum = nil,
        Exp = 1000,
        StartNum = 0
    },
    [1001] = {
        ItemID = 1001,
        Name = '皮肤2',
        Icon = 'Icon_M_Diamond',
        Quality = 2,
        Tab = 1,
        Order = 2,
        CompositeTarget = nil,
        StackNum = 1,
        CompositeNum = nil,
        Exp = 1000,
        StartNum = 0
    },
    [1002] = {
        ItemID = 1002,
        Name = '皮肤1碎片',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 1,
        Order = 100,
        CompositeTarget = 1000,
        StackNum = -1,
        CompositeNum = 60,
        Exp = 0,
        StartNum = 0
    },
    [1003] = {
        ItemID = 1003,
        Name = '皮肤2碎片',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 1,
        Order = 101,
        CompositeTarget = 1003,
        StackNum = -1,
        CompositeNum = 60,
        Exp = 0,
        StartNum = 0
    },
    [1004] = {
        ItemID = 1004,
        Name = '皮肤3',
        Icon = 'Icon_M_Diamond',
        Quality = 3,
        Tab = 1,
        Order = 3,
        CompositeTarget = nil,
        StackNum = 1,
        CompositeNum = nil,
        Exp = 1000,
        StartNum = 0
    },
    [1005] = {
        ItemID = 1005,
        Name = '拖尾特效',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 2,
        Order = 1,
        CompositeTarget = nil,
        StackNum = 1,
        CompositeNum = nil,
        Exp = 1000,
        StartNum = 0
    },
    [1006] = {
        ItemID = 1006,
        Name = '拖尾特效2',
        Icon = 'Icon_M_Diamond',
        Quality = 2,
        Tab = 2,
        Order = 2,
        CompositeTarget = nil,
        StackNum = 1,
        CompositeNum = nil,
        Exp = 1000,
        StartNum = 0
    },
    [1007] = {
        ItemID = 1007,
        Name = '拖尾特效碎片',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 2,
        Order = 100,
        CompositeTarget = 1005,
        StackNum = -1,
        CompositeNum = 100,
        Exp = 0,
        StartNum = 0
    },
    [1008] = {
        ItemID = 1008,
        Name = '拖尾特效2碎片',
        Icon = 'Icon_M_Diamond',
        Quality = 1,
        Tab = 2,
        Order = 101,
        CompositeTarget = 1006,
        StackNum = -1,
        CompositeNum = 100,
        Exp = 0,
        StartNum = 0
    },
    [9999] = {
        ItemID = 9999,
        Name = '宝箱钥匙',
        Icon = 'Icon_M_Diamond',
        Quality = 5,
        Tab = 3,
        Order = 1,
        CompositeTarget = nil,
        StackNum = -1,
        CompositeNum = nil,
        Exp = 0,
        StartNum = 1
    },
    [9998] = {
        ItemID = 9998,
        Name = '钥匙碎片',
        Icon = 'Icon_M_Diamond',
        Quality = 5,
        Tab = 3,
        Order = 2,
        CompositeTarget = 9999,
        StackNum = -1,
        CompositeNum = 10,
        Exp = 0,
        StartNum = 0
    }
}

return ItemXls
