--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/NpcEnemy.xls

local NpcEnemyXls = {
    [1] = {
        Id = 1,
        Name = 'Resign',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 10
    },
    [2] = {
        Id = 2,
        Name = 'Akoasm',
        Occupation = 1001,
        UpdateDelay = 2.5,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 9
    },
    [3] = {
        Id = 3,
        Name = 'Unfair',
        Occupation = 1004,
        UpdateDelay = 3.0,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 8
    },
    [4] = {
        Id = 4,
        Name = 'Bearish',
        Occupation = 1004,
        UpdateDelay = 1.5,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 7
    },
    [5] = {
        Id = 5,
        Name = 'Sad',
        Occupation = 1004,
        UpdateDelay = 2.0,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 6
    },
    [6] = {
        Id = 6,
        Name = 'Anonyme',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 5
    },
    [7] = {
        Id = 7,
        Name = 'Drowning',
        Occupation = 1001,
        UpdateDelay = 2.5,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 10
    },
    [8] = {
        Id = 8,
        Name = 'Tempted',
        Occupation = 1004,
        UpdateDelay = 3.0,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 9
    },
    [9] = {
        Id = 9,
        Name = 'Haggard',
        Occupation = 1004,
        UpdateDelay = 1.5,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 8
    },
    [10] = {
        Id = 10,
        Name = 'Layearn',
        Occupation = 1006,
        UpdateDelay = 2.0,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 7
    },
    [11] = {
        Id = 11,
        Name = 'Monologue',
        Occupation = 1001,
        UpdateDelay = 2.1,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 6
    },
    [12] = {
        Id = 12,
        Name = 'Kate',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 5
    },
    [13] = {
        Id = 13,
        Name = 'Warmlight',
        Occupation = 1004,
        UpdateDelay = 2.5,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 10
    },
    [14] = {
        Id = 14,
        Name = 'Catchme',
        Occupation = 1006,
        UpdateDelay = 3.0,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 9
    },
    [15] = {
        Id = 15,
        Name = 'Breathing',
        Occupation = 1006,
        UpdateDelay = 1.5,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 8
    },
    [16] = {
        Id = 16,
        Name = 'Sober',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 7
    },
    [17] = {
        Id = 17,
        Name = 'Monody',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 6
    },
    [18] = {
        Id = 18,
        Name = 'Autism',
        Occupation = 1004,
        UpdateDelay = 2.5,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 5
    },
    [19] = {
        Id = 19,
        Name = 'Nightmare',
        Occupation = 1006,
        UpdateDelay = 3.0,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 10
    },
    [20] = {
        Id = 20,
        Name = 'Scum',
        Occupation = 1006,
        UpdateDelay = 1.5,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 9
    },
    [21] = {
        Id = 21,
        Name = 'Foreverlove',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 8
    },
    [22] = {
        Id = 22,
        Name = 'Dawn',
        Occupation = 1002,
        UpdateDelay = 2.1,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 7
    },
    [23] = {
        Id = 23,
        Name = 'Yoke',
        Occupation = 1004,
        UpdateDelay = 2.5,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 6
    },
    [24] = {
        Id = 24,
        Name = 'Starry',
        Occupation = 1006,
        UpdateDelay = 3.0,
        PursuitDis = 25.0,
        AttackDis = 20.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 5
    },
    [25] = {
        Id = 25,
        Name = 'Thorns',
        Occupation = 1006,
        UpdateDelay = 1.5,
        PursuitDis = 20.0,
        AttackDis = 15.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 9
    },
    [26] = {
        Id = 26,
        Name = 'Foryou',
        Occupation = 1001,
        UpdateDelay = 2.0,
        PursuitDis = 22.0,
        AttackDis = 17.0,
        DamageRate = 0.2,
        ShootSpeedRate = 0.2,
        UpdateFrequency = 10
    }
}

return NpcEnemyXls
