--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Items.xls

local ItemDropXls = {
    [1000] = {
        [1] = {
            [1] = {
                Id = 1000,
                GroupId = 1,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1000,
                GroupId = 1,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1000,
                GroupId = 1,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 3,
                MaxRewardNum = 5,
                Weight = 1000
            },
            [4] = {
                Id = 1000,
                GroupId = 1,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 4,
                MaxRewardNum = 6,
                Weight = 1000
            },
            [5] = {
                Id = 1000,
                GroupId = 1,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        },
        [2] = {
            [1] = {
                Id = 1000,
                GroupId = 2,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1000,
                GroupId = 2,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1000,
                GroupId = 2,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 10,
                MaxRewardNum = 15,
                Weight = 1000
            },
            [4] = {
                Id = 1000,
                GroupId = 2,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 10,
                MaxRewardNum = 15,
                Weight = 1000
            },
            [5] = {
                Id = 1000,
                GroupId = 2,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        },
        [3] = {
            [1] = {
                Id = 1000,
                GroupId = 3,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1000,
                GroupId = 3,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1000,
                GroupId = 3,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 20,
                MaxRewardNum = 33,
                Weight = 1000
            },
            [4] = {
                Id = 1000,
                GroupId = 3,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 20,
                MaxRewardNum = 22,
                Weight = 1000
            },
            [5] = {
                Id = 1000,
                GroupId = 3,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        }
    },
    [1001] = {
        [1] = {
            [1] = {
                Id = 1001,
                GroupId = 1,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1001,
                GroupId = 1,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1001,
                GroupId = 1,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 3,
                MaxRewardNum = 5,
                Weight = 1000
            },
            [4] = {
                Id = 1001,
                GroupId = 1,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 4,
                MaxRewardNum = 6,
                Weight = 1000
            },
            [5] = {
                Id = 1001,
                GroupId = 1,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        },
        [2] = {
            [1] = {
                Id = 1001,
                GroupId = 2,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1001,
                GroupId = 2,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1001,
                GroupId = 2,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 10,
                MaxRewardNum = 15,
                Weight = 1000
            },
            [4] = {
                Id = 1001,
                GroupId = 2,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 10,
                MaxRewardNum = 15,
                Weight = 1000
            },
            [5] = {
                Id = 1001,
                GroupId = 2,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        },
        [3] = {
            [1] = {
                Id = 1001,
                GroupId = 3,
                SerialNum = 1,
                RewardId = 1000,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [2] = {
                Id = 1001,
                GroupId = 3,
                SerialNum = 2,
                RewardId = 1001,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            },
            [3] = {
                Id = 1001,
                GroupId = 3,
                SerialNum = 3,
                RewardId = 1002,
                MinRewardNum = 20,
                MaxRewardNum = 33,
                Weight = 1000
            },
            [4] = {
                Id = 1001,
                GroupId = 3,
                SerialNum = 4,
                RewardId = 1003,
                MinRewardNum = 20,
                MaxRewardNum = 22,
                Weight = 1000
            },
            [5] = {
                Id = 1001,
                GroupId = 3,
                SerialNum = 5,
                RewardId = 1004,
                MinRewardNum = 1,
                MaxRewardNum = 1,
                Weight = 10
            }
        }
    }
}

return ItemDropXls
