--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Level.xls

local LevelXls = {
    [1] = {
        Lv = 1,
        Stage = 1,
        Exp2Next = 10000,
        Stars = 1,
        Items = {[9999] = 1}
    },
    [2] = {
        Lv = 2,
        Stage = 1,
        Exp2Next = 11000,
        Stars = 1,
        Items = {[9999] = 1}
    },
    [3] = {
        Lv = 3,
        Stage = 1,
        Exp2Next = 12000,
        Stars = 1,
        Items = {[9999] = 1}
    },
    [4] = {
        Lv = 4,
        Stage = 1,
        Exp2Next = 13000,
        Stars = 1,
        Items = {[9999] = 1}
    },
    [5] = {
        Lv = 5,
        Stage = 1,
        Exp2Next = 14000,
        Stars = 1,
        Items = {[9999] = 1}
    },
    [6] = {
        Lv = 6,
        Stage = 1,
        Exp2Next = 15000,
        Stars = 2,
        Items = {[9999] = 1}
    },
    [7] = {
        Lv = 7,
        Stage = 1,
        Exp2Next = 16000,
        Stars = 2,
        Items = {[9999] = 1}
    },
    [8] = {
        Lv = 8,
        Stage = 1,
        Exp2Next = 17000,
        Stars = 2,
        Items = {[9999] = 1}
    },
    [9] = {
        Lv = 9,
        Stage = 1,
        Exp2Next = 18000,
        Stars = 2,
        Items = {[9999] = 1}
    },
    [10] = {
        Lv = 10,
        Stage = 2,
        Exp2Next = 19000,
        Stars = 2,
        Items = {[9999] = 1}
    },
    [11] = {
        Lv = 11,
        Stage = 2,
        Exp2Next = 20000,
        Stars = 3,
        Items = {[9999] = 1}
    },
    [12] = {
        Lv = 12,
        Stage = 2,
        Exp2Next = 21000,
        Stars = 3,
        Items = {[9999] = 1}
    },
    [13] = {
        Lv = 13,
        Stage = 2,
        Exp2Next = 22000,
        Stars = 3,
        Items = {[9999] = 1}
    },
    [14] = {
        Lv = 14,
        Stage = 2,
        Exp2Next = 23000,
        Stars = 3,
        Items = {[9999] = 1}
    },
    [15] = {
        Lv = 15,
        Stage = 2,
        Exp2Next = 24000,
        Stars = 3,
        Items = {[9999] = 1}
    },
    [16] = {
        Lv = 16,
        Stage = 2,
        Exp2Next = 25000,
        Stars = 4,
        Items = {[9999] = 1}
    },
    [17] = {
        Lv = 17,
        Stage = 2,
        Exp2Next = 26000,
        Stars = 4,
        Items = {[9999] = 1}
    },
    [18] = {
        Lv = 18,
        Stage = 2,
        Exp2Next = 27000,
        Stars = 4,
        Items = {[9999] = 1}
    },
    [19] = {
        Lv = 19,
        Stage = 2,
        Exp2Next = 28000,
        Stars = 4,
        Items = {[9999] = 1}
    },
    [20] = {
        Lv = 20,
        Stage = 3,
        Exp2Next = 29000,
        Stars = 4,
        Items = {[9999] = 1}
    },
    [21] = {
        Lv = 21,
        Stage = 3,
        Exp2Next = 30000,
        Stars = 5,
        Items = {[9999] = 1}
    },
    [22] = {
        Lv = 22,
        Stage = 3,
        Exp2Next = 31000,
        Stars = 5,
        Items = {[9999] = 1}
    },
    [23] = {
        Lv = 23,
        Stage = 3,
        Exp2Next = 32000,
        Stars = 5,
        Items = {[9999] = 1}
    },
    [24] = {
        Lv = 24,
        Stage = 3,
        Exp2Next = 33000,
        Stars = 5,
        Items = {[9999] = 1}
    },
    [25] = {
        Lv = 25,
        Stage = 3,
        Exp2Next = 34000,
        Stars = 5,
        Items = {[9999] = 1}
    },
    [26] = {
        Lv = 26,
        Stage = 3,
        Exp2Next = 35000,
        Stars = 6,
        Items = {[9999] = 1}
    },
    [27] = {
        Lv = 27,
        Stage = 3,
        Exp2Next = 36000,
        Stars = 6,
        Items = {[9999] = 1}
    },
    [28] = {
        Lv = 28,
        Stage = 3,
        Exp2Next = 37000,
        Stars = 6,
        Items = {[9999] = 1}
    },
    [29] = {
        Lv = 29,
        Stage = 3,
        Exp2Next = 38000,
        Stars = 6,
        Items = {[9999] = 1}
    },
    [30] = {
        Lv = 30,
        Stage = 4,
        Exp2Next = 39000,
        Stars = 6,
        Items = {[9999] = 1}
    },
    [31] = {
        Lv = 31,
        Stage = 4,
        Exp2Next = 40000,
        Stars = 7,
        Items = {[9999] = 1}
    },
    [32] = {
        Lv = 32,
        Stage = 4,
        Exp2Next = 41000,
        Stars = 7,
        Items = {[9999] = 1}
    },
    [33] = {
        Lv = 33,
        Stage = 4,
        Exp2Next = 42000,
        Stars = 7,
        Items = {[9999] = 1}
    },
    [34] = {
        Lv = 34,
        Stage = 4,
        Exp2Next = 43000,
        Stars = 7,
        Items = {[9999] = 1}
    },
    [35] = {
        Lv = 35,
        Stage = 4,
        Exp2Next = 44000,
        Stars = 7,
        Items = {[9999] = 1}
    },
    [36] = {
        Lv = 36,
        Stage = 4,
        Exp2Next = 45000,
        Stars = 8,
        Items = {[9999] = 1}
    },
    [37] = {
        Lv = 37,
        Stage = 4,
        Exp2Next = 46000,
        Stars = 8,
        Items = {[9999] = 1}
    },
    [38] = {
        Lv = 38,
        Stage = 4,
        Exp2Next = 47000,
        Stars = 8,
        Items = {[9999] = 1}
    },
    [39] = {
        Lv = 39,
        Stage = 4,
        Exp2Next = 48000,
        Stars = 8,
        Items = {[9999] = 1}
    },
    [40] = {
        Lv = 40,
        Stage = 5,
        Exp2Next = 49000,
        Stars = 8,
        Items = {[9999] = 1}
    },
    [41] = {
        Lv = 41,
        Stage = 5,
        Exp2Next = 50000,
        Stars = 9,
        Items = {[9999] = 1}
    },
    [42] = {
        Lv = 42,
        Stage = 5,
        Exp2Next = 51000,
        Stars = 9,
        Items = {[9999] = 1}
    },
    [43] = {
        Lv = 43,
        Stage = 5,
        Exp2Next = 52000,
        Stars = 9,
        Items = {[9999] = 1}
    },
    [44] = {
        Lv = 44,
        Stage = 5,
        Exp2Next = 53000,
        Stars = 9,
        Items = {[9999] = 1}
    },
    [45] = {
        Lv = 45,
        Stage = 5,
        Exp2Next = 54000,
        Stars = 9,
        Items = {[9999] = 1}
    },
    [46] = {
        Lv = 46,
        Stage = 5,
        Exp2Next = 55000,
        Stars = 10,
        Items = {[9999] = 1}
    },
    [47] = {
        Lv = 47,
        Stage = 5,
        Exp2Next = 56000,
        Stars = 10,
        Items = {[9999] = 1}
    },
    [48] = {
        Lv = 48,
        Stage = 5,
        Exp2Next = 57000,
        Stars = 10,
        Items = {[9999] = 1}
    },
    [49] = {
        Lv = 49,
        Stage = 5,
        Exp2Next = 58000,
        Stars = 10,
        Items = {[9999] = 1}
    },
    [50] = {
        Lv = 50,
        Stage = 6,
        Exp2Next = 59000,
        Stars = 10,
        Items = {[9999] = 1}
    }
}

return LevelXls
