--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: ./Xls/GlobalSetting.xls

local GlobalSettingXls = {
    DefaultLanguage = "CHS",
    PlayerPosition = Vector3(0,-1,0),
    PlayerRotation = Euler(90,0,0),
    MaxPlayerNumber = 100.0,
    ScoreRate = 12.5
}

return GlobalSettingXls
