--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/GlobalConfig.xls

local GlobalConfigXls = {
    Stronghold_PointRange = 2.0,
    Stronghold_SpeedPer = 30.0,
    Stronghold_SpeedUp = 30.0,
    Stronghold_SpeedMax = 50.0,
    Stronghold_PointGrade = {0.45,1},
    PlayerNum = 1.0,
    TeamMinNum = 3.0,
    Hall2GameWait = 5.0,
    GameReadyWait = 20.0,
    GameOverWaitTime = 10.0,
    BombMode_PointRange = 1.0,
    BombMode_ExplosionTime = 20.0,
    BombMode_ExplosionCount = 2.0,
    BombMode_SetTime = 2.0,
    BombMode_RemoveTime = 2.0,
    BombMode_TeamAMaxBombs = 1.0,
    BombMode_ExplosionDamage = 100.0,
    BombMode_DamageWeight = {Bone_Head = 10,Bone_R_Hand = 10,Bone_L_Hand = 10,Bone_Pelvis = 10,Bone_R_Foot = 10,Bone_L_Foot = 10},
    BombMode_ExplosionRange = 4.0,
    NoticeMsgCD = 2.0,
    NoticeMsgTime = 2.0,
    CelebrationAni = {"SocialHappy","SocialApplause","SocialCheer"},
    ContinuousKill =    {
        [2] = { Img = 'Img_2Kill', Content = 'DOUBLE KILL!', Sound = 102 },
        [3] = { Img = 'Img_3Kill', Content = 'TRIPLE KILL!', Sound = 103 },
        [4] = { Img = 'Img_4Kill', Content = 'MULTI KILL!', Sound = 104 },
        [5] = { Img = 'Img_5Kill', Content = 'RAMPAGE!', Sound = 105 },
        [6] = { Img = 'Img_5Kill', Content = 'UNSTOPPABLE!!', Sound = 105 },
        [7] = { Img = 'Img_5Kill', Content = 'GOD-LIKE!', Sound = 105 },
        [8] = { Img = 'Img_5Kill', Content = 'DOMINATING!', Sound = 105 },
    },
    DieCameraMoveTime = 0.5,
    DieCameraHoldTime = 3.0,
    DieCameraHeight = 15.0,
    DieCameraXRotation = 10.0,
    DefaultGunId = 1001.0,
    NameLengthShow = 5.0,
    LoadingShowTime = 4.0,
    QualityFrame = {Middle2High = 35,Low2Middle = 30},
    DefaultFPS = "Middle",
    FrameUpdateDelay = 0.2,
    LogicListLength = 50.0,
    RenderListLength = 20.0,
    Lv_BaseEXP = 20000.0,
    Lv_PerformanceEXPRate = 1.0,
    Lv_MVPEXP = 500.0,
    Lv_WinEXP = 200.0,
    Item_KeyID = 9999.0
}

return GlobalConfigXls
