--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Mode.xls

local ModeXls = {
    [1] = {
        ModeId = 1,
        Name = '占点玩法',
        Des = '需要在点中一定时间后才会将此点占领,占领的点会产出积分,首先达到目标积分的一方获胜',
        WinScore = 1000,
        KillScore = {20,20,20,20,50,50,50,50},
        CustomParams = {CaptureScore = {2, 10},AttackKillScore = 50,ProtectKillScore = 50}
    },
    [2] = {
        ModeId = 2,
        Name = '爆破模式',
        Des = '都是对的多多大',
        WinScore = 1000,
        KillScore = {20,20,20,20,50,50,50,50},
        CustomParams = {SetTNT = 50,RemoveTNT= 50}
    },
    [3] = {
        ModeId = 3,
        Name = '杀人玩法',
        Des = '一定时间内,一方的总击杀数达到指定数量即此方获胜',
        WinScore = 1000,
        KillScore = {75,75,75,100,100,100,135,135},
        CustomParams = nil
    }
}

return ModeXls
