--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: ./Xls/Sound.xls

local SoundXls = {
    test_01 = {
        Type = 1,
        ID = 'test_01',
        IsLoop = nil,
        Volume = nil,
        FileName = '',
        Detail = '',
        Duration = nil,
        CoverPlay = nil
    }
}

return SoundXls
