--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Items.xls

local TabXls = {
    [1] = {
        TabID = 1,
        Name = '枪械皮肤',
        Order = 1
    },
    [2] = {
        TabID = 2,
        Name = '拖尾特效',
        Order = 2
    },
    [3] = {
        TabID = 3,
        Name = '其他',
        Order = 3
    }
}

return TabXls
