--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Items.xls

local ItemExteriorXls = {
    [1000] = {
        ItemID = 1000,
        Name = 'UZI SKIN',
        Res = '',
        IsGunSkin = true,
        GunId = 1001,
        SkinId = 2,
        HangNode = ''
    },
    [1001] = {
        ItemID = 1001,
        Name = 'AKM SKIN',
        Res = '',
        IsGunSkin = true,
        GunId = 2004,
        SkinId = 2,
        HangNode = ''
    },
    [1004] = {
        ItemID = 1004,
        Name = 'M249 SKIN',
        Res = '',
        IsGunSkin = true,
        GunId = 5002,
        SkinId = 2,
        HangNode = ''
    },
    [1005] = {
        ItemID = 1005,
        Name = '拖尾特效',
        Res = 'BloodPoolGrowing',
        IsGunSkin = false,
        GunId = nil,
        SkinId = nil,
        HangNode = 'Bone_Pelvis'
    },
    [1006] = {
        ItemID = 1006,
        Name = '拖尾特效2',
        Res = 'HealRecover',
        IsGunSkin = false,
        GunId = nil,
        SkinId = nil,
        HangNode = 'Bone_Head'
    }
}

return ItemExteriorXls
