--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/GlobalSetting.xls

local GlobalSettingXls = {
    DefaultLanguage = "CHS",
    PlayerPosition = Vector3(0,-1,0),
    PlayerRotation = Euler(90,0,0),
    MaxPlayerNumber = 100.0,
    ScoreRate = 12.5
}

return GlobalSettingXls
