--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Items.xls

local QualityXls = {
    [1] = {
        QualityID = 1,
        Name = '白',
        Image = ''
    },
    [2] = {
        QualityID = 2,
        Name = '绿',
        Image = ''
    },
    [3] = {
        QualityID = 3,
        Name = '蓝',
        Image = ''
    },
    [4] = {
        QualityID = 4,
        Name = '紫',
        Image = ''
    },
    [5] = {
        QualityID = 5,
        Name = '橙',
        Image = ''
    }
}

return QualityXls
