--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Sound.xls

local SoundXls = {
    [100] = {
        ID = 100,
        IsLoop = false,
        Volume = 50,
        FileName = 'KillSound',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [101] = {
        ID = 101,
        IsLoop = false,
        Volume = 50,
        FileName = 'Firework',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [102] = {
        ID = 102,
        IsLoop = false,
        Volume = 50,
        FileName = 'Legender2k',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [103] = {
        ID = 103,
        IsLoop = false,
        Volume = 50,
        FileName = 'Legender3k',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [104] = {
        ID = 104,
        IsLoop = false,
        Volume = 50,
        FileName = 'Legender4k',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [105] = {
        ID = 105,
        IsLoop = false,
        Volume = 50,
        FileName = 'Legender5k',
        Detail = '1.0',
        Duration = 6.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [106] = {
        ID = 106,
        IsLoop = false,
        Volume = 50,
        FileName = 'SelectSwitch',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [107] = {
        ID = 107,
        IsLoop = false,
        Volume = 50,
        FileName = 'SelectComplete',
        Detail = '1.0',
        Duration = 2.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [109] = {
        ID = 109,
        IsLoop = false,
        Volume = 50,
        FileName = 'ReturnHall',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [110] = {
        ID = 110,
        IsLoop = false,
        Volume = 50,
        FileName = 'ChooseWeapon',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [112] = {
        ID = 112,
        IsLoop = false,
        Volume = 50,
        FileName = 'ConfirmWeapon',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [113] = {
        ID = 113,
        IsLoop = false,
        Volume = 50,
        FileName = 'GameWin',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [114] = {
        ID = 114,
        IsLoop = false,
        Volume = 50,
        FileName = 'GameLose',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [115] = {
        ID = 115,
        IsLoop = false,
        Volume = 50,
        FileName = 'GameResultShow',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = false,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [116] = {
        ID = 116,
        IsLoop = false,
        Volume = 50,
        FileName = 'SwitchTab',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [117] = {
        ID = 117,
        IsLoop = false,
        Volume = 50,
        FileName = 'StartReady',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    },
    [118] = {
        ID = 118,
        IsLoop = false,
        Volume = 50,
        FileName = 'MatchComplete',
        Detail = '1.0',
        Duration = 1.0,
        CoverPlay = true,
        MaxDistance = 60.0,
        MinDistance = 60.0
    }
}

return SoundXls
