--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Clothes_Female.xls

local Clothes_FemaleXls = {
    Clothes = {
        [1] = {
            Female_Cloth_Part = 'Clothes',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Clothes',
            Value = 2,
            Des = 'Female_Chest_TshirtShort_A001'
        },
        [3] = {
            Female_Cloth_Part = 'Clothes',
            Value = 3,
            Des = 'Female_Chest_TshirtShort_A002'
        },
        [4] = {
            Female_Cloth_Part = 'Clothes',
            Value = 4,
            Des = 'Female_Chest_TshirtShort_A003'
        },
        [5] = {
            Female_Cloth_Part = 'Clothes',
            Value = 5,
            Des = 'Female_Chest_TshirtShort_A004'
        },
        [6] = {
            Female_Cloth_Part = 'Clothes',
            Value = 6,
            Des = 'Female_Chest_TshirtShort_A005'
        },
        [7] = {
            Female_Cloth_Part = 'Clothes',
            Value = 7,
            Des = 'Female_Chest_TshirtShort_A006'
        },
        [8] = {
            Female_Cloth_Part = 'Clothes',
            Value = 8,
            Des = 'Female_Chest_TshirtShort_A007'
        },
        [9] = {
            Female_Cloth_Part = 'Clothes',
            Value = 9,
            Des = 'Female_Chest_TshirtShort_A008'
        },
        [10] = {
            Female_Cloth_Part = 'Clothes',
            Value = 10,
            Des = 'Female_Chest_TshirtShort_A009'
        },
        [11] = {
            Female_Cloth_Part = 'Clothes',
            Value = 11,
            Des = 'Female_Chest_TshirtShort_A010'
        },
        [12] = {
            Female_Cloth_Part = 'Clothes',
            Value = 12,
            Des = 'Female_Chest_SweaterLong_A001'
        },
        [13] = {
            Female_Cloth_Part = 'Clothes',
            Value = 13,
            Des = 'Female_Chest_SweaterLong_A002'
        },
        [14] = {
            Female_Cloth_Part = 'Clothes',
            Value = 14,
            Des = 'Female_Chest_SweaterLong_A003'
        },
        [15] = {
            Female_Cloth_Part = 'Clothes',
            Value = 15,
            Des = 'Female_Chest_SweaterLong_A004'
        },
        [16] = {
            Female_Cloth_Part = 'Clothes',
            Value = 16,
            Des = 'Female_Chest_SweaterLong_A005'
        },
        [17] = {
            Female_Cloth_Part = 'Clothes',
            Value = 17,
            Des = 'Female_Chest_SweaterLong_A006'
        },
        [18] = {
            Female_Cloth_Part = 'Clothes',
            Value = 18,
            Des = 'Female_Chest_SweaterLong_A007'
        },
        [19] = {
            Female_Cloth_Part = 'Clothes',
            Value = 19,
            Des = 'Female_Chest_SweaterLong_A008'
        },
        [20] = {
            Female_Cloth_Part = 'Clothes',
            Value = 20,
            Des = 'Female_Chest_SweaterLong_A009'
        },
        [21] = {
            Female_Cloth_Part = 'Clothes',
            Value = 21,
            Des = 'Female_Chest_SweaterLong_A010'
        },
        [22] = {
            Female_Cloth_Part = 'Clothes',
            Value = 22,
            Des = 'Female_Chest_SweaterLong_A011'
        },
        [23] = {
            Female_Cloth_Part = 'Clothes',
            Value = 23,
            Des = 'Female_Chest_SweaterLong_A012'
        },
        [24] = {
            Female_Cloth_Part = 'Clothes',
            Value = 24,
            Des = 'Female_001Jacket'
        },
        [25] = {
            Female_Cloth_Part = 'Clothes',
            Value = 25,
            Des = 'Female_002Jacket'
        },
        [26] = {
            Female_Cloth_Part = 'Clothes',
            Value = 26,
            Des = 'Female_003Jacket'
        },
        [27] = {
            Female_Cloth_Part = 'Clothes',
            Value = 27,
            Des = 'Female_004Jacket_01'
        },
        [28] = {
            Female_Cloth_Part = 'Clothes',
            Value = 28,
            Des = 'Female_004Jacket_02'
        },
        [29] = {
            Female_Cloth_Part = 'Clothes',
            Value = 29,
            Des = 'Female_005Jacket'
        },
        [30] = {
            Female_Cloth_Part = 'Clothes',
            Value = 30,
            Des = 'Female_006Tshirt'
        },
        [31] = {
            Female_Cloth_Part = 'Clothes',
            Value = 31,
            Des = 'Female_007Tshirt'
        },
        [32] = {
            Female_Cloth_Part = 'Clothes',
            Value = 32,
            Des = 'Female_Chest_SweaterLong_007'
        },
        [33] = {
            Female_Cloth_Part = 'Clothes',
            Value = 33,
            Des = 'Female_009Jacket'
        },
        [34] = {
            Female_Cloth_Part = 'Clothes',
            Value = 34,
            Des = 'Female_010Jacket'
        },
        [35] = {
            Female_Cloth_Part = 'Clothes',
            Value = 35,
            Des = 'Female_011Jacket'
        },
        [36] = {
            Female_Cloth_Part = 'Clothes',
            Value = 36,
            Des = 'Female_Chest_Jacket_002'
        },
        [37] = {
            Female_Cloth_Part = 'Clothes',
            Value = 37,
            Des = 'Female_013Jacket'
        },
        [38] = {
            Female_Cloth_Part = 'Clothes',
            Value = 38,
            Des = 'Female_Chest_Shirt_India_001'
        },
        [39] = {
            Female_Cloth_Part = 'Clothes',
            Value = 39,
            Des = 'Female_Chest_JacketIndiaSilk_001'
        },
        [40] = {
            Female_Cloth_Part = 'Clothes',
            Value = 40,
            Des = 'Female_AviatorJacket'
        },
        [41] = {
            Female_Cloth_Part = 'Clothes',
            Value = 41,
            Des = 'Female_MexicJacket'
        },
        [42] = {
            Female_Cloth_Part = 'Clothes',
            Value = 42,
            Des = 'Female_SpaceJacket'
        },
        [43] = {
            Female_Cloth_Part = 'Clothes',
            Value = 43,
            Des = 'Female_BaseballJacket'
        },
        [44] = {
            Female_Cloth_Part = 'Clothes',
            Value = 44,
            Des = 'Female_UniverJacket'
        },
        [45] = {
            Female_Cloth_Part = 'Clothes',
            Value = 45,
            Des = 'Female_UniverJacket_01'
        },
        [46] = {
            Female_Cloth_Part = 'Clothes',
            Value = 46,
            Des = 'Female_Chest_ArmorGriffin_001'
        },
        [47] = {
            Female_Cloth_Part = 'Clothes',
            Value = 47,
            Des = 'Unisex_Chest_ArmorIron_001'
        }
    },
    Trousers = {
        [1] = {
            Female_Cloth_Part = 'Trousers',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Trousers',
            Value = 2,
            Des = 'Female_001Pants'
        },
        [3] = {
            Female_Cloth_Part = 'Trousers',
            Value = 3,
            Des = 'Female_002Trousers'
        },
        [4] = {
            Female_Cloth_Part = 'Trousers',
            Value = 4,
            Des = 'Female_003Pants'
        },
        [5] = {
            Female_Cloth_Part = 'Trousers',
            Value = 5,
            Des = 'Female_004Pants'
        },
        [6] = {
            Female_Cloth_Part = 'Trousers',
            Value = 6,
            Des = 'Female_005Trousers'
        },
        [7] = {
            Female_Cloth_Part = 'Trousers',
            Value = 7,
            Des = 'Female_006Trousers'
        },
        [8] = {
            Female_Cloth_Part = 'Trousers',
            Value = 8,
            Des = 'Female_007Pants'
        },
        [9] = {
            Female_Cloth_Part = 'Trousers',
            Value = 9,
            Des = 'Female_Leg_SportPantsLong_001'
        },
        [10] = {
            Female_Cloth_Part = 'Trousers',
            Value = 10,
            Des = 'Female_009Pants'
        },
        [11] = {
            Female_Cloth_Part = 'Trousers',
            Value = 11,
            Des = 'Female_010Pants'
        },
        [12] = {
            Female_Cloth_Part = 'Trousers',
            Value = 12,
            Des = 'Female_011Trousers'
        },
        [13] = {
            Female_Cloth_Part = 'Trousers',
            Value = 13,
            Des = 'Female_Leg_CasualPantsShort_006'
        },
        [14] = {
            Female_Cloth_Part = 'Trousers',
            Value = 14,
            Des = 'Female_013Trousers'
        },
        [15] = {
            Female_Cloth_Part = 'Trousers',
            Value = 15,
            Des = 'Female_Leg_Pants_India_001'
        },
        [16] = {
            Female_Cloth_Part = 'Trousers',
            Value = 16,
            Des = 'Female_Leg_TrousersIndiaSilk_001'
        },
        [17] = {
            Female_Cloth_Part = 'Trousers',
            Value = 17,
            Des = 'Female_AviatorTrousers'
        },
        [18] = {
            Female_Cloth_Part = 'Trousers',
            Value = 18,
            Des = 'Female_MexicTrousers'
        },
        [19] = {
            Female_Cloth_Part = 'Trousers',
            Value = 19,
            Des = 'Female_SpaceTrousers'
        },
        [20] = {
            Female_Cloth_Part = 'Trousers',
            Value = 20,
            Des = 'Female_BaseballTrousers'
        },
        [21] = {
            Female_Cloth_Part = 'Trousers',
            Value = 21,
            Des = 'Female_UniverTrousers'
        },
        [22] = {
            Female_Cloth_Part = 'Trousers',
            Value = 22,
            Des = 'Female_UniverTrousers_01'
        },
        [23] = {
            Female_Cloth_Part = 'Trousers',
            Value = 23,
            Des = 'Female_Leg_ArmorGriffin_001'
        },
        [24] = {
            Female_Cloth_Part = 'Trousers',
            Value = 24,
            Des = 'Female_Leg_ArmorIron_001'
        },
        [25] = {
            Female_Cloth_Part = 'Trousers',
            Value = 25,
            Des = 'Female_WendigoTrousers'
        },
        [26] = {
            Female_Cloth_Part = 'Trousers',
            Value = 26,
            Des = 'Female_NutTrousers'
        },
        [27] = {
            Female_Cloth_Part = 'Trousers',
            Value = 27,
            Des = 'Female_Leg_PantsLRobtBear_001'
        },
        [28] = {
            Female_Cloth_Part = 'Trousers',
            Value = 28,
            Des = 'Female_Leg_PantsClownfish_001'
        },
        [29] = {
            Female_Cloth_Part = 'Trousers',
            Value = 29,
            Des = 'Female_Leg_PantsWaste_001'
        },
        [30] = {
            Female_Cloth_Part = 'Trousers',
            Value = 30,
            Des = 'Female_Leg_TrousersBiker_001'
        },
        [31] = {
            Female_Cloth_Part = 'Trousers',
            Value = 31,
            Des = 'Female_Leg_TrousersBiker01_001'
        },
        [32] = {
            Female_Cloth_Part = 'Trousers',
            Value = 32,
            Des = 'Female_Leg_TrousersLMotor_001'
        },
        [33] = {
            Female_Cloth_Part = 'Trousers',
            Value = 33,
            Des = 'Female_Leg_PantsShine_001'
        },
        [34] = {
            Female_Cloth_Part = 'Trousers',
            Value = 34,
            Des = 'Female_Leg_TrousersSteam_001'
        },
        [35] = {
            Female_Cloth_Part = 'Trousers',
            Value = 35,
            Des = 'Female_Leg_PantsLRobtEva_001'
        },
        [36] = {
            Female_Cloth_Part = 'Trousers',
            Value = 36,
            Des = 'Female_Leg_PantsLRobtEva_002'
        },
        [37] = {
            Female_Cloth_Part = 'Trousers',
            Value = 37,
            Des = 'Female_Leg_PantsLAI_001'
        }
    },
    Hair = {
        [1] = {
            Female_Cloth_Part = 'Hair',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Hair',
            Value = 2,
            Des = 'Hair_Brown01F'
        },
        [3] = {
            Female_Cloth_Part = 'Hair',
            Value = 3,
            Des = 'Hair_Blonde01F'
        },
        [4] = {
            Female_Cloth_Part = 'Hair',
            Value = 4,
            Des = 'Hair_Orange01F'
        },
        [5] = {
            Female_Cloth_Part = 'Hair',
            Value = 5,
            Des = 'Hair_White01F'
        },
        [6] = {
            Female_Cloth_Part = 'Hair',
            Value = 6,
            Des = 'Hair_Blue01F'
        },
        [7] = {
            Female_Cloth_Part = 'Hair',
            Value = 7,
            Des = 'Female_Head_Hair_015'
        }
    },
    Hands = {
        [1] = {
            Female_Cloth_Part = 'Hands',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Hands',
            Value = 2,
            Des = 'Male_GLeather01'
        },
        [3] = {
            Female_Cloth_Part = 'Hands',
            Value = 3,
            Des = 'Male_AviatorGloves'
        },
        [4] = {
            Female_Cloth_Part = 'Hands',
            Value = 4,
            Des = 'Male_SpaceGloves'
        },
        [5] = {
            Female_Cloth_Part = 'Hands',
            Value = 5,
            Des = 'Male_BaseballGloves'
        },
        [6] = {
            Female_Cloth_Part = 'Hands',
            Value = 6,
            Des = 'Male_UniverGloves'
        },
        [7] = {
            Female_Cloth_Part = 'Hands',
            Value = 7,
            Des = 'Male_UniverGloves_01'
        },
        [8] = {
            Female_Cloth_Part = 'Hands',
            Value = 8,
            Des = 'Unisex_Hand_GlovesGriffin_001'
        },
        [9] = {
            Female_Cloth_Part = 'Hands',
            Value = 9,
            Des = 'Unisex_Hand_GlovesIron_001'
        },
        [10] = {
            Female_Cloth_Part = 'Hands',
            Value = 10,
            Des = 'Male_WendigoGloves'
        },
        [11] = {
            Female_Cloth_Part = 'Hands',
            Value = 11,
            Des = 'Unisex_Hand_GlovesSki_001'
        },
        [12] = {
            Female_Cloth_Part = 'Hands',
            Value = 12,
            Des = 'Unisex_Hand_GlovesRobtBear_001'
        },
        [13] = {
            Female_Cloth_Part = 'Hands',
            Value = 13,
            Des = 'Female_Hand_GlovesBiker_001'
        },
        [14] = {
            Female_Cloth_Part = 'Hands',
            Value = 14,
            Des = 'Female_Hand_GlovesMotor_001'
        },
        [15] = {
            Female_Cloth_Part = 'Hands',
            Value = 15,
            Des = 'Unisex_Hand_GlovesRobtEva_001'
        },
        [16] = {
            Female_Cloth_Part = 'Hands',
            Value = 16,
            Des = 'Unisex_Hand_GlovesRobtEva_002'
        }
    },
    Shoes = {
        [1] = {
            Female_Cloth_Part = 'Shoes',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Shoes',
            Value = 2,
            Des = 'Female_001Boots'
        },
        [3] = {
            Female_Cloth_Part = 'Shoes',
            Value = 3,
            Des = 'Unisex_Feet_CanvasShoes_A001'
        },
        [4] = {
            Female_Cloth_Part = 'Shoes',
            Value = 4,
            Des = 'Unisex_Feet_CanvasShoes_A002'
        },
        [5] = {
            Female_Cloth_Part = 'Shoes',
            Value = 5,
            Des = 'Unisex_Feet_CanvasShoes_A003'
        },
        [6] = {
            Female_Cloth_Part = 'Shoes',
            Value = 6,
            Des = 'Unisex_Feet_CanvasShoes_A004'
        },
        [7] = {
            Female_Cloth_Part = 'Shoes',
            Value = 7,
            Des = 'Unisex_Feet_CanvasShoes_A005'
        },
        [8] = {
            Female_Cloth_Part = 'Shoes',
            Value = 8,
            Des = 'Unisex_Feet_CanvasShoes_A006'
        },
        [9] = {
            Female_Cloth_Part = 'Shoes',
            Value = 9,
            Des = 'Unisex_Feet_CanvasShoes_A007'
        },
        [10] = {
            Female_Cloth_Part = 'Shoes',
            Value = 10,
            Des = 'Unisex_Feet_CanvasShoes_A008'
        },
        [11] = {
            Female_Cloth_Part = 'Shoes',
            Value = 11,
            Des = 'Unisex_Feet_CanvasShoes_A009'
        },
        [12] = {
            Female_Cloth_Part = 'Shoes',
            Value = 12,
            Des = 'Unisex_Feet_CanvasShoes_A010'
        },
        [13] = {
            Female_Cloth_Part = 'Shoes',
            Value = 13,
            Des = 'Female_002Boots'
        },
        [14] = {
            Female_Cloth_Part = 'Shoes',
            Value = 14,
            Des = 'Female_003Shoes'
        },
        [15] = {
            Female_Cloth_Part = 'Shoes',
            Value = 15,
            Des = 'Female_004Shoes'
        },
        [16] = {
            Female_Cloth_Part = 'Shoes',
            Value = 16,
            Des = 'Female_005Shoes'
        },
        [17] = {
            Female_Cloth_Part = 'Shoes',
            Value = 17,
            Des = 'Female_006Boots'
        },
        [18] = {
            Female_Cloth_Part = 'Shoes',
            Value = 18,
            Des = 'Unisex_Feet_BasketballShoes_003'
        },
        [19] = {
            Female_Cloth_Part = 'Shoes',
            Value = 19,
            Des = 'Female_009Boots'
        },
        [20] = {
            Female_Cloth_Part = 'Shoes',
            Value = 20,
            Des = 'Female_010Boots'
        },
        [21] = {
            Female_Cloth_Part = 'Shoes',
            Value = 21,
            Des = 'Female_010Shoes'
        },
        [22] = {
            Female_Cloth_Part = 'Shoes',
            Value = 22,
            Des = 'Female_011Shoes'
        },
        [23] = {
            Female_Cloth_Part = 'Shoes',
            Value = 23,
            Des = 'Female_Feet_RainBoots_001'
        },
        [24] = {
            Female_Cloth_Part = 'Shoes',
            Value = 24,
            Des = 'Female_013Boots'
        },
        [25] = {
            Female_Cloth_Part = 'Shoes',
            Value = 25,
            Des = 'Female_Feet_Shoes_India_001'
        },
        [26] = {
            Female_Cloth_Part = 'Shoes',
            Value = 26,
            Des = 'Female_Feet_ShoesIndiaSilk_001'
        },
        [27] = {
            Female_Cloth_Part = 'Shoes',
            Value = 27,
            Des = 'Male_AviatorShoes'
        },
        [28] = {
            Female_Cloth_Part = 'Shoes',
            Value = 28,
            Des = 'Male_MexicBoots'
        },
        [29] = {
            Female_Cloth_Part = 'Shoes',
            Value = 29,
            Des = 'Male_SpaceBoots'
        },
        [30] = {
            Female_Cloth_Part = 'Shoes',
            Value = 30,
            Des = 'Male_BaseballShoes'
        },
        [31] = {
            Female_Cloth_Part = 'Shoes',
            Value = 31,
            Des = 'Male_UniverShoes'
        },
        [32] = {
            Female_Cloth_Part = 'Shoes',
            Value = 32,
            Des = 'Male_UniverShoes_01'
        },
        [33] = {
            Female_Cloth_Part = 'Shoes',
            Value = 33,
            Des = 'Unisex_Feet_ShoesGriffin_001'
        },
        [34] = {
            Female_Cloth_Part = 'Shoes',
            Value = 34,
            Des = 'Unisex_Feet_ShoesIron_001'
        },
        [35] = {
            Female_Cloth_Part = 'Shoes',
            Value = 35,
            Des = 'Male_WendigoShoes'
        },
        [36] = {
            Female_Cloth_Part = 'Shoes',
            Value = 36,
            Des = 'Female_NutBoots'
        },
        [37] = {
            Female_Cloth_Part = 'Shoes',
            Value = 37,
            Des = 'Female_Feet_ShoesRobtBear_001'
        },
        [38] = {
            Female_Cloth_Part = 'Shoes',
            Value = 38,
            Des = 'Female_Feet_BootsWaste_001'
        }
    },
    Face = {
        [1] = {
            Female_Cloth_Part = 'Face',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'Face',
            Value = 2,
            Des = 'Female_test1'
        },
        [3] = {
            Female_Cloth_Part = 'Face',
            Value = 3,
            Des = 'Female_test2'
        },
        [4] = {
            Female_Cloth_Part = 'Face',
            Value = 4,
            Des = 'Female_test3'
        },
        [5] = {
            Female_Cloth_Part = 'Face',
            Value = 5,
            Des = 'Female_test5'
        },
        [6] = {
            Female_Cloth_Part = 'Face',
            Value = 6,
            Des = 'Female_test6'
        },
        [7] = {
            Female_Cloth_Part = 'Face',
            Value = 7,
            Des = 'Female_test7'
        },
        [8] = {
            Female_Cloth_Part = 'Face',
            Value = 8,
            Des = 'Female_test8'
        },
        [9] = {
            Female_Cloth_Part = 'Face',
            Value = 9,
            Des = 'Female_test9'
        },
        [10] = {
            Female_Cloth_Part = 'Face',
            Value = 10,
            Des = 'Female_test10'
        }
    },
    SkinColor = {
        [1] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 1,
            Des = 'DefaultFemale'
        },
        [2] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 2,
            Des = 'Color2'
        },
        [3] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 3,
            Des = 'Color3'
        },
        [4] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 4,
            Des = 'Color4'
        },
        [5] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 5,
            Des = 'Color5'
        },
        [6] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 6,
            Des = 'Color6'
        },
        [7] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 7,
            Des = 'Color7'
        },
        [8] = {
            Female_Cloth_Part = 'SkinColor',
            Value = 8,
            Des = 'Color8'
        }
    },
    HeadAccessory = {
        [1] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 1,
            Des = 'Empty_Head'
        },
        [2] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 2,
            Des = 'Female_ComHat001'
        },
        [3] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 3,
            Des = 'Male_ComHat003'
        },
        [4] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 4,
            Des = 'Male_ComHat004'
        },
        [5] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 5,
            Des = 'Male_ComHat005'
        },
        [6] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 6,
            Des = 'Male_ComHat006'
        },
        [7] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 7,
            Des = 'Male_ComHat007'
        },
        [8] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 8,
            Des = 'Male_008Hat'
        },
        [9] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 9,
            Des = 'Male_010Hat'
        },
        [10] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 10,
            Des = 'Male_012Hat'
        },
        [11] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 11,
            Des = 'Female_ComHelmet001'
        },
        [12] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 12,
            Des = 'Male_Head_ComHelmet_002'
        },
        [13] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 13,
            Des = 'Male_ComHelmet003'
        },
        [14] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 14,
            Des = 'Male_ComHelmet004'
        },
        [15] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 15,
            Des = 'Male_ComHelmet005'
        },
        [16] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 16,
            Des = 'Female_Head_Beanie_002'
        },
        [17] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 17,
            Des = 'Female_013Hat'
        },
        [18] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 18,
            Des = 'Male_AviatorHat'
        },
        [19] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 19,
            Des = 'Male_MexicHat'
        },
        [20] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 20,
            Des = 'Male_SpaceHelmet'
        },
        [21] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 21,
            Des = 'Male_Baseball01Hat'
        },
        [22] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 22,
            Des = 'Male_Baseball02Hat'
        },
        [23] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 23,
            Des = 'Male_UniverHelmet'
        },
        [24] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 24,
            Des = 'Male_UniverHelmet_01'
        },
        [25] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 25,
            Des = 'Female_Head_HelmetGriffin_001'
        },
        [26] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 26,
            Des = 'Unisex_Head_HelmetIron_001'
        },
        [27] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 27,
            Des = 'Male_Wendigo_Helmet'
        },
        [28] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 28,
            Des = 'Female_Nut_Helmet'
        },
        [29] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 29,
            Des = 'Unisex_Head_CapSki_001'
        },
        [30] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 30,
            Des = 'Female_Head_HelmetRobtBear_001'
        },
        [31] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 31,
            Des = 'Female_Head_HelmetClownfish_001'
        },
        [32] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 32,
            Des = 'Female_Head_HelmetBiker_001'
        },
        [33] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 33,
            Des = 'Female_Head_HelmetMotor_001'
        },
        [34] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 34,
            Des = 'Female_Head_HelmetSteam_001'
        },
        [35] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 35,
            Des = 'Unisex_Head_HelmetRobtEva_001'
        },
        [36] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 36,
            Des = 'Unisex_Head_HelmetRobtEva_002'
        },
        [37] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 37,
            Des = 'Unisex_Head_HelmetAI_001'
        },
        [38] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 38,
            Des = 'Unisex_Head_JewelsMadMax_001'
        },
        [39] = {
            Female_Cloth_Part = 'HeadAccessory',
            Value = 39,
            Des = 'Female_Zombies02_Helmet'
        }
    },
    NeckAccessory = {
        [1] = {
            Female_Cloth_Part = 'NeckAccessory',
            Value = 1,
            Des = 'Empty_Neck'
        },
        [2] = {
            Female_Cloth_Part = 'NeckAccessory',
            Value = 2,
            Des = 'Female_Motor_Lace'
        },
        [3] = {
            Female_Cloth_Part = 'NeckAccessory',
            Value = 3,
            Des = 'Female_Waste_Lace'
        },
        [4] = {
            Female_Cloth_Part = 'NeckAccessory',
            Value = 4,
            Des = 'Female_Biker_Lace'
        },
        [5] = {
            Female_Cloth_Part = 'NeckAccessory',
            Value = 5,
            Des = 'Male_AviatorScarf'
        }
    },
    LegAccessory = {
        [1] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 1,
            Des = 'Empty_Legs'
        },
        [2] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 2,
            Des = 'Male_AviatorKneepad'
        },
        [3] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 3,
            Des = 'Unisex_Knee_PadGriffin_001'
        },
        [4] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 4,
            Des = 'Unisex_Knee_PadIron_001'
        },
        [5] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 5,
            Des = 'Unisex_Knee_PadPolice_001'
        },
        [6] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 6,
            Des = 'Unisex_Knee_PadWaste_001'
        },
        [7] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 7,
            Des = 'Unisex_Knee_PadBiker_001'
        },
        [8] = {
            Female_Cloth_Part = 'LegAccessory',
            Value = 8,
            Des = 'Unisex_Knee_PadMadMax_001'
        }
    },
    HandsAccessory = {
        [1] = {
            Female_Cloth_Part = 'HandsAccessory',
            Value = 1,
            Des = 'Empty_Hands'
        },
        [2] = {
            Female_Cloth_Part = 'HandsAccessory',
            Value = 2,
            Des = 'Female_001Watch'
        },
        [3] = {
            Female_Cloth_Part = 'HandsAccessory',
            Value = 3,
            Des = 'Female_Arm_BraceletClownfish_001'
        },
        [4] = {
            Female_Cloth_Part = 'HandsAccessory',
            Value = 4,
            Des = 'Male_010Wrist'
        },
        [5] = {
            Female_Cloth_Part = 'HandsAccessory',
            Value = 5,
            Des = 'Male_011Wrist'
        }
    },
    BodyAccessory = {
        [1] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 1,
            Des = 'Empty_Body'
        },
        [2] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 2,
            Des = 'Male_009Bag'
        },
        [3] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 3,
            Des = 'Male_012Bag'
        },
        [4] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 4,
            Des = 'Female_Chest_Hobo_002'
        },
        [5] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 5,
            Des = 'Male_AviatorBag'
        },
        [6] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 6,
            Des = 'Male_MexicUkulele'
        },
        [7] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 7,
            Des = 'Male_SpaceBag'
        },
        [8] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 8,
            Des = 'Male_BaseballBag'
        },
        [9] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 9,
            Des = 'Male_UniverBag'
        },
        [10] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 10,
            Des = 'Male_WendigoBag'
        },
        [11] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 11,
            Des = 'Unisex_Back_BackpackPolice_001'
        },
        [12] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 12,
            Des = 'Unisex_Back_BackpackSki_001'
        },
        [13] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 13,
            Des = 'Female_Back_BackpackSteam_001'
        },
        [14] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 14,
            Des = 'Male_Zombies04Bag'
        },
        [15] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 15,
            Des = 'Female_Zombies05Bag'
        },
        [16] = {
            Female_Cloth_Part = 'BodyAccessory',
            Value = 16,
            Des = 'Male_Zombies06Bag'
        }
    },
    WaistAccessory = {
        [1] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 1,
            Des = 'Empty_Waist'
        },
        [2] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 2,
            Des = 'LifeBuoy'
        },
        [3] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 3,
            Des = 'Unisex_Pelvis_Lifebuoy_Duck_01'
        },
        [4] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 4,
            Des = 'Unisex_Pelvis_Lifebuoy_Donut_01'
        },
        [5] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 5,
            Des = 'Unisex_Pelvis_Lifebuoy_Donut_02'
        },
        [6] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 6,
            Des = 'Unisex_Pelvis_Lifebuoy_Watermelon'
        },
        [7] = {
            Female_Cloth_Part = 'WaistAccessory',
            Value = 7,
            Des = 'Unisex_Pelvis_Lifebuoy_Tire'
        }
    },
    FaceAccessory = {
        [1] = {
            Female_Cloth_Part = 'FaceAccessory',
            Value = 1,
            Des = 'Empty_Face'
        },
        [2] = {
            Female_Cloth_Part = 'FaceAccessory',
            Value = 2,
            Des = 'Glasses'
        },
        [3] = {
            Female_Cloth_Part = 'FaceAccessory',
            Value = 3,
            Des = 'Female_MadMax_Glasses'
        },
        [4] = {
            Female_Cloth_Part = 'FaceAccessory',
            Value = 4,
            Des = 'HeadSet'
        }
    }
}

return Clothes_FemaleXls
