--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/LanguagePack.xls

local LanguagePackXls = {
    Example1_Des1_1_house = {
        ID = 'Example1_Des1_1_house',
        CHS = '我真的很想%s吃饭',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des2_1_house = {
        ID = 'Example1_Des2_1_house',
        CHS = '做什么',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des1_1_MMM = {
        ID = 'Example1_Des1_1_MMM',
        CHS = '我饿了',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des2_1_MMM = {
        ID = 'Example1_Des2_1_MMM',
        CHS = '工作是什么',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des1_1_ddd = {
        ID = 'Example1_Des1_1_ddd',
        CHS = '到底什么时候能吃饭',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des2_1_ddd = {
        ID = 'Example1_Des2_1_ddd',
        CHS = '我是谁',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des1_2_farm = {
        ID = 'Example1_Des1_2_farm',
        CHS = '今天晚上吃什么',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des2_2_farm = {
        ID = 'Example1_Des2_2_farm',
        CHS = '我从哪里来',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des1_2_MMM = {
        ID = 'Example1_Des1_2_MMM',
        CHS = '下班就去吃饭吧',
        CHT = '',
        EN = '',
        JP = ''
    },
    Example1_Des2_2_MMM = {
        ID = 'Example1_Des2_2_MMM',
        CHS = '就这样吧',
        CHT = '',
        EN = '',
        JP = ''
    }
}

return LanguagePackXls
