--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Message.xls

local MessageXls = {
    [1001] = {
        MsgId = 1001,
        Content = 'Frequent operation, please wait'
    },
    [1002] = {
        MsgId = 1002,
        Content = 'Gun CD, please wait'
    },
    [1003] = {
        MsgId = 1003,
        Content = 'Need to be near the spawn point'
    },
    [1004] = {
        MsgId = 1004,
        Content = 'Only an attacker can place a bomb'
    },
    [1005] = {
        MsgId = 1005,
        Content = 'Only the defense can dismantle the bomb'
    },
    [1006] = {
        MsgId = 1006,
        Content = 'There is no place for bombs at this point'
    },
    [1007] = {
        MsgId = 1007,
        Content = 'There are no bombs that can be dismantled at this point'
    },
    [1008] = {
        MsgId = 1008,
        Content = 'Incorrect bomb index'
    },
    [1009] = {
        MsgId = 1009,
        Content = 'A bomb has been placed at this point'
    },
    [1010] = {
        MsgId = 1010,
        Content = 'Get a bomb'
    },
    [1011] = {
        MsgId = 1011,
        Content = 'The number of bombs has been capped'
    },
    [1012] = {
        MsgId = 1012,
        Content = 'No bombs'
    },
    [9999] = {
        MsgId = 9999,
        Content = 'Test,Quailty Change'
    },
    [2000] = {
        MsgId = 2000,
        Content = 'Your device is stuck and automatically reduces the image quality.'
    }
}

return MessageXls
