--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/FortConfig.xls

local FortConfigXls = {
    [1001] = {
        Id = 1001,
        Des = '炮台1',
        MaxHp = 500.0,
        Damage = 5.0,
        ShootSpeed = 1.0,
        Distance = 15.0
    },
    [1002] = {
        Id = 1002,
        Des = '炮台2',
        MaxHp = 500.0,
        Damage = 6.0,
        ShootSpeed = 1.0,
        Distance = 15.0
    },
    [1003] = {
        Id = 1003,
        Des = '炮台3',
        MaxHp = 500.0,
        Damage = 7.0,
        ShootSpeed = 1.0,
        Distance = 16.0
    },
    [1004] = {
        Id = 1004,
        Des = '炮台4',
        MaxHp = 500.0,
        Damage = 8.0,
        ShootSpeed = 1.0,
        Distance = 17.0
    },
    [1005] = {
        Id = 1005,
        Des = '炮台5',
        MaxHp = 500.0,
        Damage = 9.0,
        ShootSpeed = 1.0,
        Distance = 18.0
    },
    [1006] = {
        Id = 1006,
        Des = '炮台6',
        MaxHp = 500.0,
        Damage = 10.0,
        ShootSpeed = 1.0,
        Distance = 19.0
    },
    [1007] = {
        Id = 1007,
        Des = '炮台7',
        MaxHp = 500.0,
        Damage = 11.0,
        ShootSpeed = 1.0,
        Distance = 20.0
    },
    [1008] = {
        Id = 1008,
        Des = '炮台8',
        MaxHp = 500.0,
        Damage = 12.0,
        ShootSpeed = 1.0,
        Distance = 21.0
    }
}

return FortConfigXls
