--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: ./Xls/ExampleTable1.xlsx

local Example1Xls = {
    [1] = {
        house = {
            id = 1,
            name = 'house',
            use_money = 1000,
            use_food = 2.33,
            is_init = true,
            defense = 100,
            args_int_arr = {1, 2, 3},
            args_float_arr = {1.23, 2, 3.23},
            args_string_arr = {'sdf', '23e', 's'},
            args_bool_arr = {true, false, true},
            args_vect2 = Vector2(-1, 0.5),
            args_vect3 = Vector3(2, 0.3, -4),
            args_euler = EulerDegree(12, 23, 43),
            args_color = Color(129, 12, 3, 0),
            args_lua = function() print(23) end,
            Des1 = 'Example1_Des1_1_house',
            Des2 = 'Example1_Des2_1_house'
        },
        MMM = {
            id = 1,
            name = 'MMM',
            use_money = 123,
            use_food = 336.2,
            is_init = true,
            defense = nil,
            args_int_arr = {1, 2, 3},
            args_float_arr = {1, 2.3445, 3},
            args_string_arr = {'你好', '你在哪'},
            args_bool_arr = {true, false},
            args_vect2 = Vector2(0, 4),
            args_vect3 = Vector3(-2, 3, 5),
            args_euler = nil,
            args_color = nil,
            args_lua = {a = 2, b='234'},
            Des1 = 'Example1_Des1_1_MMM',
            Des2 = 'Example1_Des2_1_MMM'
        },
        ddd = {
            id = 1,
            name = 'ddd',
            use_money = 456,
            use_food = 222.33665,
            is_init = false,
            defense = 130,
            args_int_arr = {3, 2, 5},
            args_float_arr = {3, 2, 2.5},
            args_string_arr = {'我在这里啊', '你在那', '呢'},
            args_bool_arr = {false, true},
            args_vect2 = Vector2(2, 0.5),
            args_vect3 = Vector3(0.6, 3, -8.4),
            args_euler = nil,
            args_color = nil,
            args_lua = nil,
            Des1 = 'Example1_Des1_1_ddd',
            Des2 = 'Example1_Des2_1_ddd'
        }
    },
    [2] = {
        farm = {
            id = 2,
            name = 'farm',
            use_money = 100,
            use_food = 220.0,
            is_init = false,
            defense = 200,
            args_int_arr = {2, 3},
            args_float_arr = {200.3, 3, 234.23},
            args_string_arr = {'df', 'ssd', 'dd', 'dd'},
            args_bool_arr = nil,
            args_vect2 = nil,
            args_vect3 = nil,
            args_euler = nil,
            args_color = nil,
            args_lua = nil,
            Des1 = 'Example1_Des1_2_farm',
            Des2 = 'Example1_Des2_2_farm'
        },
        MMM = {
            id = 2,
            name = 'MMM',
            use_money = nil,
            use_food = 22.1,
            is_init = nil,
            defense = 234,
            args_int_arr = {3, 6, 6, 7},
            args_float_arr = {3, 6.3, 6, 7},
            args_string_arr = {'ss', 'd', 'd', 'd'},
            args_bool_arr = {true, true},
            args_vect2 = nil,
            args_vect3 = nil,
            args_euler = nil,
            args_color = nil,
            args_lua = "还没有添加检查",
            Des1 = 'Example1_Des1_2_MMM',
            Des2 = 'Example1_Des2_2_MMM'
        }
    }
}

return Example1Xls
