--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/Level.xls

local StageXls = {
    [1] = {
        Stage = 1,
        FrameImage = ''
    },
    [2] = {
        Stage = 2,
        FrameImage = ''
    },
    [3] = {
        Stage = 3,
        FrameImage = ''
    },
    [4] = {
        Stage = 4,
        FrameImage = ''
    },
    [5] = {
        Stage = 5,
        FrameImage = ''
    },
    [6] = {
        Stage = 6,
        FrameImage = ''
    },
    [7] = {
        Stage = 7,
        FrameImage = ''
    },
    [8] = {
        Stage = 8,
        FrameImage = ''
    },
    [9] = {
        Stage = 9,
        FrameImage = ''
    },
    [10] = {
        Stage = 10,
        FrameImage = ''
    }
}

return StageXls
