--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/ExampleTable1.xlsx

local Example2Xls = {
    [1] = {
        id = 1,
        name = 'house',
        use_money = 1000,
        use_food = 2.33,
        is_init = true,
        defense = 100,
        args1 = {1, 2, 3},
        args2 = {1.23, 2, 3.23},
        args3 = {'sdf', '23e', 's'},
        args4 = {true, false, true}
    },
    [2] = {
        id = 2,
        name = '你好吗？',
        use_money = 123,
        use_food = 336.2,
        is_init = true,
        defense = nil,
        args1 = {1, 2, 3},
        args2 = {1, 2.3445, 3},
        args3 = {'你好', '你在哪'},
        args4 = {true, false}
    },
    [3] = {
        id = 3,
        name = '',
        use_money = 456,
        use_food = 222.33665,
        is_init = false,
        defense = 130,
        args1 = {3, 2, 5},
        args2 = {3, 2, 2.5},
        args3 = {'我在这里啊', '你在那', '呢'},
        args4 = {false, true}
    },
    [4] = {
        id = 4,
        name = 'farm',
        use_money = 100,
        use_food = 220.0,
        is_init = false,
        defense = 200,
        args1 = {2, 3},
        args2 = {200.3, 3, 234.23},
        args3 = {'df', 'ssd', 'dd', 'dd'},
        args4 = nil
    },
    [5] = {
        id = 5,
        name = 'house5',
        use_money = nil,
        use_food = 22.1,
        is_init = nil,
        defense = 234,
        args1 = {3, 6, 6, 7},
        args2 = {3, 6.3, 6, 7},
        args3 = {'ss', 'd', 'd', 'd'},
        args4 = {true, true}
    },
    [6] = {
        id = 6,
        name = 'horse3',
        use_money = 200,
        use_food = nil,
        is_init = false,
        defense = 333,
        args1 = nil,
        args2 = nil,
        args3 = {'2e', 'w', 'e', 'we'},
        args4 = {false, false, false, false}
    }
}

return Example2Xls
