--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/ActAnimations.xlsx

local ActAnimXls = {
    [1] = {
        ID = 1,
        Mode = 1,
        ShowName = '鞠躬',
        --anim = {'anim_human_social_applause_begin', 'anim_human_social_applause_loop', 'anim_human_social_applause_end'},
        anim = {'Idle', 'SocialBow', 'Idle'},
        dur = {0.3, 2, 0.3},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [2] = {
        ID = 2,
        Mode = 1,
        ShowName = '打招呼',
        anim = {'Idle', 'Exhibition12', 'Idle'},
        dur = {0.01, 2, 0.01},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [3] = {
        ID = 3,
        Mode = 1,
        ShowName = '落败',
        anim = {'anim_human_social_fail_begin', 'anim_human_social_fail_loop', 'anim_human_social_fail_end'},
        dur = {0.8, -1, 0.6},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [4] = {
        ID = 4,
        Mode = 1,
        ShowName = '大笑',
        anim = {'anim_human_social_laughing_begin', 'anim_human_social_laughing_loop', 'anim_human_social_laughing_end'},
        dur = {0.5, 2, 1},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [5] = {
        ID = 5,
        Mode = 1,
        ShowName = '鼓掌',
        anim = {'anim_human_social_applause_begin', 'anim_human_social_applause_loop', 'anim_human_social_applause_end'},
        dur = {0.3, -1, 0.3},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [6] = {
        ID = 6,
        Mode = 1,
        ShowName = '装死',
        anim = {'anim_human_social_playdead_begin', 'anim_human_social_playdead_loop', 'anim_human_social_playdead_end'},
        dur = {3, -1, 0.5},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [7] = {
        ID = 7,
        Mode = 2,
        ShowName = '挥手',
        anim = {'anim_human_sit_wave_begin', 'anim_human_sit_wave', 'anim_human_sit_wave_end'},
        dur = {0.3, -1, 0.5},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [8] = {
        ID = 8,
        Mode = 2,
        ShowName = '翘腿',
        anim = {'anim_human_sit_crosslegs_begin', 'anim_human_sit_crosslegs', 'anim_human_sit_crosslegs_end'},
        dur = {1.5, -1, 1},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [9] = {
        ID = 9,
        Mode = 2,
        ShowName = '托腮',
        anim = {'anim_human_sit_doubt_begin', 'anim_human_sit_doubt', 'anim_human_sit_doubt_end'},
        dur = {1, -1, 0.5},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    },
    [10] = {
        ID = 10,
        Mode = 2,
        ShowName = '助威',
        anim = {'anim_human_sit_cheer_begin', 'anim_human_sit_cheer', 'anim_human_sit_cheer_end'},
        dur = {0.3, -1, 0.3},
        speed = 1.0,
        layer = 0,
        transIn = 0.2,
        transOut = 0.2,
        isInterrupt = true,
        isLoop = true,
        speedScale = 1.0
    }
}

return ActAnimXls
